services:
  # Mandatory part
  mariadb:
    container_name: mariadb
    env_file: ../secrets/.env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    expose:
      - "3306"
    restart: on-failure
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
      - "4242:4242"
    depends_on:
      - wordpress
    restart: on-failure
  wordpress:
    container_name: wordpress
    env_file: ../secrets/.env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: on-failure
  # Bonus part
  adminer:
    container_name: adminer
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure
  portainer:
    container_name: portainer
    build:
      context: requirements/bonus/portainer
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    ports:
      - "9443:9443"
    privileged: true
    restart: on-failure
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'
  portainer_data:
networks:
  inception:
    driver: bridge
